import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { BookList, DetailedBook } from '../types/book';

const books = [
	{
		key: '1',
		title: 'The Great Gatsby',
		author_name: [ 'F. Scott Fitzgerald' ],
		first_publish_year: 1925,
		cover_edition_key: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg',
		ratings_average: 4.2,
		ratings_count: 2100,
		number_of_pages_median: 180,
		subtitle: 'A Novel',
		first_publish_date: '1925-04-10',
		subjects: [ 'American literature' ],
		subject_places: [ 'New York' ],
		subject_people: [ 'Jay Gatsby' ],
		subject_times: [ '1920s' ],
	},
	{
		key: '2',
		title: 'To Kill a Mockingbird',
		author_name: [ 'Harper Lee' ],
		first_publish_year: 1960,
		ratings_average: 4.5,
		ratings_count: 3400,
		number_of_pages_median: 281,
		first_publish_date: '1960-07-11',
		subjects: [ 'American literature', 'Social issues' ],
		subject_places: [ 'Maycomb' ],
		subject_people: [ 'Atticus Finch' ],
		subject_times: [ '1930s' ],
	},
	{
		key: '3',
		title: '1984',
		author_name: [ 'George Orwell' ],
		first_publish_year: 1949,
		cover_edition_key: 'https://allbook.by/wp-content/uploads/2016/12/p_8_5_5_855-1984.jpg',
		ratings_average: 4.4,
		ratings_count: 3000,
		number_of_pages_median: 328,
		first_publish_date: '1949-06-08',
		subjects: [ 'Dystopia', 'Totalitarianism' ],
		subject_places: [ 'Oceania' ],
		subject_people: [ 'Big Brother' ],
		subject_times: [ 'Future' ],
	},
	{
		key: '4',
		title: 'Brave New World',
		author_name: [ 'Aldous Huxley' ],
		first_publish_year: 1932,
		cover_edition_key: 'https://cdn2.penguin.com.au/covers/400/9781784876258.jpg',
		ratings_average: 4.3,
		ratings_count: 2300,
		number_of_pages_median: 268,
		first_publish_date: '1932-08-01',
		subjects: [ 'Dystopia', 'Science fiction' ],
		subject_places: [ 'World State' ],
		subject_people: [ 'John the Savage' ],
		subject_times: [ 'Future' ],
	},
	{
		key: '5',
		title: 'Moby-Dick',
		author_name: [ 'Herman Melville' ],
		first_publish_year: 1851,
		ratings_average: 3.8,
		ratings_count: 1700,
		number_of_pages_median: 635,
		first_publish_date: '1851-10-18',
		subjects: [ 'Adventure', 'Whaling' ],
		subject_places: [ 'Pacific Ocean' ],
		subject_people: [ 'Captain Ahab', 'Ishmael' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '6',
		title: 'Pride and Prejudice',
		author_name: [ 'Jane Austen' ],
		first_publish_year: 1813,
		cover_edition_key: 'https://m.media-amazon.com/images/I/712P0p5cXIL._AC_UF1000,1000_QL80_.jpg',
		ratings_average: 4.3,
		ratings_count: 2600,
		number_of_pages_median: 432,
		first_publish_date: '1813-01-28',
		subjects: [ 'Romance', 'Social class' ],
		subject_places: [ 'England' ],
		subject_people: [ 'Elizabeth Bennet', 'Mr. Darcy' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '7',
		title: 'War and Peace',
		author_name: [ 'Leo Tolstoy' ],
		first_publish_year: 1869,
		ratings_average: 4.1,
		ratings_count: 2200,
		number_of_pages_median: 1225,
		first_publish_date: '1869-01-01',
		subjects: [ 'War', 'Russia' ],
		subject_places: [ 'Russia' ],
		subject_people: [ 'Pierre Bezukhov', 'Andrei Bolkonsky' ],
		subject_times: [ 'Napoleonic Wars' ],
	},
	{
		key: '8',
		title: 'Crime and Punishment',
		author_name: [ 'Fyodor Dostoevsky' ],
		first_publish_year: 1866,
		cover_edition_key: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ56DtGkTgSQ3O8e_4iVfjyVgblNOJs0HJZLg&s',
		ratings_average: 4.2,
		ratings_count: 2900,
		number_of_pages_median: 671,
		first_publish_date: '1866-01-01',
		subjects: [ 'Psychological fiction' ],
		subject_places: [ 'St. Petersburg' ],
		subject_people: [ 'Raskolnikov' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '9',
		title: 'The Catcher in the Rye',
		author_name: [ 'J.D. Salinger' ],
		first_publish_year: 1951,
		ratings_average: 3.9,
		ratings_count: 1900,
		number_of_pages_median: 277,
		first_publish_date: '1951-07-16',
		subjects: [ 'Coming of age' ],
		subject_places: [ 'New York' ],
		subject_people: [ 'Holden Caulfield' ],
		subject_times: [ '1950s' ],
	},
	{
		key: '10',
		title: 'The Hobbit',
		author_name: [ 'J.R.R. Tolkien' ],
		first_publish_year: 1937,
		ratings_average: 4.7,
		ratings_count: 4700,
		number_of_pages_median: 310,
		first_publish_date: '1937-09-21',
		subjects: [ 'Fantasy' ],
		subject_places: [ 'Middle-earth' ],
		subject_people: [ 'Bilbo Baggins' ],
		subject_times: [ 'Third Age' ],
	},
	{
		key: '11',
		title: 'Fahrenheit 451',
		author_name: [ 'Ray Bradbury' ],
		first_publish_year: 1953,
		cover_edition_key: 'https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg',
		ratings_average: 4.0,
		ratings_count: 2500,
		number_of_pages_median: 249,
		first_publish_date: '1953-10-19',
		subjects: [ 'Dystopia', 'Censorship' ],
		subject_places: [ 'Future' ],
		subject_people: [ 'Guy Montag' ],
		subject_times: [ 'Future' ],
	},
	{
		key: '12',
		title: 'The Lord of the Rings',
		author_name: [ 'J.R.R. Tolkien' ],
		first_publish_year: 1954,
		cover_edition_key: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1566425108l/33.jpg',
		ratings_average: 4.9,
		ratings_count: 6000,
		number_of_pages_median: 1137,
		first_publish_date: '1954-07-29',
		subjects: [ 'Fantasy' ],
		subject_places: [ 'Middle-earth' ],
		subject_people: [ 'Frodo Baggins', 'Sauron' ],
		subject_times: [ 'Third Age' ],
	},
	{
		key: '13',
		title: 'Jane Eyre',
		author_name: [ 'Charlotte Brontë' ],
		first_publish_year: 1847,
		cover_edition_key: 'https://m.media-amazon.com/images/I/81pwJjgcwwL._AC_UF894,1000_QL80_.jpg',
		ratings_average: 4.1,
		ratings_count: 2800,
		number_of_pages_median: 507,
		first_publish_date: '1847-10-16',
		subjects: [ 'Gothic fiction', 'Romance' ],
		subject_places: [ 'England' ],
		subject_people: [ 'Jane Eyre', 'Mr. Rochester' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '14',
		title: 'The Picture of Dorian Gray',
		author_name: [ 'Oscar Wilde' ],
		first_publish_year: 1890,
		cover_edition_key: 'https://images.booksense.com/images/742/714/9781912714742.jpg',
		ratings_average: 4.0,
		ratings_count: 3200,
		number_of_pages_median: 254,
		first_publish_date: '1890-06-20',
		subjects: [ 'Philosophical fiction' ],
		subject_places: [ 'London' ],
		subject_people: [ 'Dorian Gray' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '15',
		title: 'Wuthering Heights',
		author_name: [ 'Emily Brontë' ],
		first_publish_year: 1847,
		cover_edition_key: 'https://m.media-amazon.com/images/I/81unikMK30L._AC_UF1000,1000_QL80_.jpg',
		ratings_average: 4.0,
		ratings_count: 3100,
		number_of_pages_median: 416,
		first_publish_date: '1847-12-01',
		subjects: [ 'Gothic fiction', 'Romance' ],
		subject_places: [ 'Yorkshire' ],
		subject_people: [ 'Heathcliff', 'Catherine Earnshaw' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '16',
		title: 'The Brothers Karamazov',
		author_name: [ 'Fyodor Dostoevsky' ],
		first_publish_year: 1880,
		ratings_average: 4.5,
		ratings_count: 2200,
		number_of_pages_median: 796,
		first_publish_date: '1880-11-01',
		subjects: [ 'Philosophical fiction' ],
		subject_places: [ 'Russia' ],
		subject_people: [ 'Karamazov brothers' ],
		subject_times: [ '19th century' ],
	},
	{
		key: '17',
		title: 'The Grapes of Wrath',
		author_name: [ 'John Steinbeck' ],
		first_publish_year: 1939,
		cover_edition_key: 'https://images.booksense.com/images/379/009/9789357009379.jpg',
		ratings_average: 4.2,
		ratings_count: 2300,
		number_of_pages_median: 464,
		first_publish_date: '1939-04-14',
		subjects: [ 'Great Depression', 'Social issues' ],
		subject_places: [ 'Oklahoma', 'California' ],
		subject_people: [ 'Tom Joad' ],
		subject_times: [ '1930s' ],
	},
	{
		key: '18',
		title: 'One Hundred Years of Solitude',
		author_name: [ 'Gabriel García Márquez' ],
		first_publish_year: 1967,
		ratings_average: 4.6,
		ratings_count: 5000,
		number_of_pages_median: 417,
		first_publish_date: '1967-06-05',
		subjects: [ 'Magical realism' ],
		subject_places: [ 'Macondo' ],
		subject_people: [ 'Buendía family' ],
		subject_times: [ 'Colonial era' ],
	},
	{
		key: '19',
		title: 'The Old Man and the Sea',
		author_name: [ 'Ernest Hemingway' ],
		first_publish_year: 1952,
		ratings_average: 4.1,
		ratings_count: 3600,
		number_of_pages_median: 127,
		first_publish_date: '1952-09-01',
		subjects: [ 'Adventure', 'Literary fiction' ],
		subject_places: [ 'Cuba' ],
		subject_people: [ 'Santiago' ],
		subject_times: [ '20th century' ],
	},
	{
		key: '20',
		title: 'The Stranger',
		author_name: [ 'Albert Camus' ],
		first_publish_year: 1942,
		ratings_average: 4.0,
		ratings_count: 3400,
		number_of_pages_median: 123,
		first_publish_date: '1942-05-01',
		subjects: [ 'Existentialism', 'Absurdism' ],
		subject_places: [ 'Algeria' ],
		subject_people: [ 'Meursault' ],
		subject_times: [ '20th century' ],
	},
];

@Injectable({
	providedIn: 'root',
})
export class BookService {
	private readonly _url = 'https://openlibrary.org';

	constructor(private http: HttpClient) {
	}

	getList(
		searchValue: string,
		page: number,
		limit: number
	): Observable<BookList> {
		// return this.http.get<BookList>(
		//   `${this._url}/search.json?q=${searchValue}&page=${page}&limit=${limit}`
		// );

		const filteredBooks = books.filter((book) =>
			book.title.toLowerCase().includes(searchValue.toLowerCase())
		);

		return searchValue.length > 0
			? of({
				numFound: filteredBooks.length,
				docs: filteredBooks.slice((page - 1) * limit, page * limit),
			})
			: of({ numFound: 0, docs: [] });
	}

	get(key: string): Observable<DetailedBook> {
		// return this.http.get<DetailedBook>(`${this._url}${key}.json`);

		return of(books.find((book) => book.key === key) as DetailedBook);
	}
}
